basePath: /
definitions:
  domain.Status:
    enum:
    - PENDING
    - RUNNING
    - COMPLETED
    - FAILED
    - CANCELED
    type: string
    x-enum-varnames:
    - StatusPending
    - StatusRunning
    - StatusCompleted
    - StatusFailed
    - StatusCancelled
  domain.Task:
    properties:
      created_at:
        type: string
      duration:
        description: |-
          Duration of the task execution
          example: 3m0s
        type: string
      ended_at:
        type: string
      id:
        type: string
      result:
        type: string
      started_at:
        type: string
      status:
        $ref: '#/definitions/domain.Status'
    type: object
  domain.TaskListItem:
    properties:
      duration:
        type: string
      id:
        type: string
      status:
        type: string
    type: object
  phttp.ErrorResponse:
    properties:
      message:
        example: something went wrong
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Сервис управления задачами
  title: Tasks API
  version: "1.0"
paths:
  /health:
    get:
      description: Проверка доступности сервиса
      produces:
      - text/plain
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Healthcheck
      tags:
      - health
  /tasks:
    post:
      description: Инициализирует задачу со статусом Pending и возвращает её с сгенерированным
        ID
      produces:
      - application/json
      responses:
        "200":
          description: Задача успешно создана
          schema:
            $ref: '#/definitions/domain.Task'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/phttp.ErrorResponse'
      summary: Создать новую задачу
      tags:
      - tasks
  /tasks/{id}:
    delete:
      description: Удаляет задачу из системы по её идентификатору
      parameters:
      - description: ID задачи
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/phttp.ErrorResponse'
      summary: Удалить задачу по ID
      tags:
      - tasks
    get:
      description: Возвращает задачу по её идентификатору
      parameters:
      - description: ID задачи
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Задача найдена
          schema:
            $ref: '#/definitions/domain.Task'
        "404":
          description: Задача не найдена
          schema:
            $ref: '#/definitions/phttp.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/phttp.ErrorResponse'
      summary: Получить задачу по ID
      tags:
      - tasks
  /tasks/{id}/cancel:
    put:
      description: Прерывает выполнение задачи, если она ещё не завершена
      parameters:
      - description: ID задачи
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: Задача отменена
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Задача не найдена
          schema:
            $ref: '#/definitions/phttp.ErrorResponse'
        "500":
          description: Внутренняя ошибка
          schema:
            $ref: '#/definitions/phttp.ErrorResponse'
      summary: Отменить задачу
      tags:
      - tasks
  /tasks/all:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.TaskListItem'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/phttp.ErrorResponse'
      summary: Получить список всех задач
      tags:
      - tasks
  /tasks/filter:
    get:
      description: Фильтрует задачи по id, status, возвращает пагинацию
      parameters:
      - description: ID задачи (точное совпадение)
        in: query
        name: id
        type: string
      - description: Статус задачи
        enum:
        - pending
        - running
        - completed
        - failed
        - cancelled
        in: query
        name: status
        type: string
      - description: Максимум задач в ответе (default=10)
        in: query
        name: limit
        type: integer
      - description: Сдвиг (default=0)
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.TaskListItem'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/phttp.ErrorResponse'
      summary: Фильтр и пагинация задач
      tags:
      - tasks
swagger: "2.0"
